version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    image: web:app
    container_name: app_django_container
    command: python manage.py runserver 0.0.0.0:8000